version: '3'
services:
  {{cookiecutter.service_name}}:
    container_name: {{cookiecutter.service_name}}
    image: {{cookiecutter.service_name_dash_case}}:latest
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ../../.prod.env
    networks:
      - {{cookiecutter.docker_compose_project_name}}_network
    depends_on:
      - "{{cookiecutter.service_name}}_mongodb"

  {{cookiecutter.service_name}}_mongodb:
    container_name: {{cookiecutter.service_name}}_mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - {{cookiecutter.service_name}}_mongodb_volume:/data/db
    networks:
      - {{cookiecutter.docker_compose_project_name}}_network

networks:
  {{cookiecutter.docker_compose_project_name}}_network:
      driver: bridge

volumes:
  {{cookiecutter.service_name}}_mongodb_volume:
